package com.apothekeammarienplatz.impfzertifikate;
// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class NavigierezuZertifikatenTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void navigierezuZertifikaten() {
        driver.get("https://www.mein-apothekenportal.de/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector(".inline-block path")).click();
        driver.findElement(By.linkText("Dashboard")).click();
        driver.findElement(By.linkText("Digitales Impfzertifikat")).click();
    }
}
